//! File walker with gitignore and generated-file filtering.

use ignore::WalkBuilder;
use recon_core::lang::Language;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

/// Default ignore patterns for generated/vendored code.
const GENERATED_MARKERS: &[&str] = &[
    "DO NOT EDIT",
    "@generated",
    "Code generated by",
    "AUTO-GENERATED",
    "automatically generated",
];

/// Aho-Corasick automaton for single-pass generated-file marker detection.
fn generated_ac() -> &'static aho_corasick::AhoCorasick {
    static AC: OnceLock<aho_corasick::AhoCorasick> = OnceLock::new();
    AC.get_or_init(|| aho_corasick::AhoCorasick::new(GENERATED_MARKERS).expect("valid patterns"))
}

/// Aho-Corasick automaton for vendored path segment + suffix detection.
fn vendored_ac() -> &'static aho_corasick::AhoCorasick {
    static AC: OnceLock<aho_corasick::AhoCorasick> = OnceLock::new();
    AC.get_or_init(|| {
        let patterns = [
            "/node_modules/",
            "/target/",
            "/dist/",
            "/build/",
            "/.next/",
            "/.venv/",
            "/__pycache__/",
            "/vendor/",
            "/third_party/",
            "/generated/",
            "/.git/",
            ".min.js",
            ".bundle.js",
            ".pb.go",
            ".generated.",
        ];
        aho_corasick::AhoCorasick::new(patterns).expect("valid patterns")
    })
}

/// Walk a directory, yielding paths that should be indexed.
/// Uses default max file size of 2MB.
pub fn walk_repo(root: &Path) -> Vec<PathBuf> {
    walk_repo_with_limit(root, 2_097_152)
}

/// Walk a directory with a configurable max file size.
pub fn walk_repo_with_limit(root: &Path, max_file_size: u64) -> Vec<PathBuf> {
    let mut paths = Vec::new();
    let walker = WalkBuilder::new(root)
        .hidden(true)
        .git_ignore(true)
        .git_global(true)
        .git_exclude(true)
        .build();

    for entry in walker {
        let entry = match entry {
            Ok(e) => e,
            Err(_) => continue,
        };
        if !entry.file_type().is_some_and(|ft| ft.is_file()) {
            continue;
        }
        let path = entry.path();
        let lang = Language::from_path(path);
        if lang == Language::Unknown {
            continue;
        }
        if let Ok(meta) = entry.metadata() {
            if meta.len() > max_file_size {
                continue;
            }
        }
        let path_str = path.to_string_lossy();
        if is_vendored(&path_str) {
            continue;
        }
        paths.push(path.to_path_buf());
    }
    paths
}

/// Walk a directory and apply extra ignore patterns from `.recon/config.toml`.
///
/// This keeps the serve/startup file gate aligned with the indexer walk:
/// gitignore + built-in vendor filters + user-configured ignore patterns.
pub fn walk_repo_with_ignores(
    root: &Path,
    max_file_size: u64,
    ignore_patterns: &[String],
) -> Vec<PathBuf> {
    let paths = walk_repo_with_limit(root, max_file_size);
    if ignore_patterns.is_empty() {
        return paths;
    }

    let patterns: Vec<String> = ignore_patterns
        .iter()
        .map(|p| p.trim())
        .filter(|p| !p.is_empty())
        .map(|p| p.replace('\\', "/"))
        .collect();
    if patterns.is_empty() {
        return paths;
    }

    let globset = build_ignore_globset(&patterns);
    paths
        .into_iter()
        .filter(|path| {
            let rel = path.strip_prefix(root).unwrap_or(path);
            let rel_str = rel.to_string_lossy().replace('\\', "/");
            let glob_match = globset.as_ref().is_some_and(|set| set.is_match(&rel_str));
            !glob_match && !patterns.iter().any(|pat| ignore_match(&rel_str, pat))
        })
        .collect()
}

fn build_ignore_globset(patterns: &[String]) -> Option<globset::GlobSet> {
    let mut builder = globset::GlobSetBuilder::new();
    let mut added = false;
    for pattern in patterns {
        let trimmed = pattern.trim_matches('/');
        let candidates: Vec<String> = if has_glob_meta(pattern) {
            vec![pattern.to_string()]
        } else if pattern.contains('/') {
            vec![pattern.to_string(), trimmed.to_string()]
        } else {
            vec![pattern.to_string(), format!("**/{trimmed}/**")]
        };
        for candidate in candidates {
            if let Ok(glob) = globset::Glob::new(&candidate) {
                builder.add(glob);
                added = true;
            }
        }
    }
    added.then(|| builder.build().ok()).flatten()
}

fn has_glob_meta(pattern: &str) -> bool {
    pattern
        .as_bytes()
        .iter()
        .any(|b| matches!(b, b'*' | b'?' | b'[' | b']' | b'{' | b'}'))
}

fn ignore_match(path: &str, pattern: &str) -> bool {
    if pattern.is_empty() {
        return false;
    }
    let path = path.trim_start_matches("./");
    let pattern = pattern.trim_start_matches("./").trim_matches('/');
    if path == pattern {
        return true;
    }
    if path.starts_with(pattern) {
        if let Some(next) = path.as_bytes().get(pattern.len()) {
            return *next == b'/' || *next == b'.';
        }
        return true;
    }
    path.split('/').any(|part| part == pattern)
}

/// Check if a path looks like a generated file by scanning first 8 lines.
pub fn is_generated(path: &Path) -> bool {
    use std::io::{BufRead, BufReader};

    let file = match std::fs::File::open(path) {
        Ok(f) => f,
        Err(_) => return false,
    };
    let reader = BufReader::with_capacity(4096, file);
    let ac = generated_ac();
    for line in reader.lines().take(8) {
        let line = match line {
            Ok(l) => l,
            Err(_) => return false,
        };
        if ac.is_match(&line) {
            return true;
        }
    }
    false
}

/// Check if already-read file content looks generated (first 8 lines).
///
/// Use this instead of [`is_generated`] when the file content has already been
/// read into memory, to avoid a redundant file open + read.
pub fn is_generated_content(content: &[u8]) -> bool {
    let text = match std::str::from_utf8(content) {
        Ok(t) => t,
        Err(_) => return false,
    };
    let ac = generated_ac();
    let mut newlines = 0;
    let cutoff = text
        .find(|c: char| {
            if c == '\n' {
                newlines += 1;
                newlines >= 8
            } else {
                false
            }
        })
        .map_or(text.len(), |pos| pos + 1);
    ac.is_match(&text[..cutoff])
}

/// Check if a path looks vendored or generated by common toolchains.
///
/// Uses a pre-compiled Aho-Corasick automaton for O(n) single-pass matching
/// against all vendor path segments and file suffixes.
pub fn is_vendored(path: &str) -> bool {
    let normalized = path.replace('\\', "/");
    let wrapped = if normalized.starts_with('/') {
        normalized
    } else {
        format!("/{normalized}")
    };
    vendored_ac().is_match(&wrapped)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vendored_detection() {
        assert!(is_vendored("/foo/node_modules/bar.js"));
        assert!(is_vendored("node_modules/bar.js"));
        assert!(is_vendored("/foo/target/debug/thing.rs"));
        assert!(is_vendored("target/debug/thing.rs"));
        assert!(!is_vendored("/src/main.rs"));
    }

    #[test]
    fn vendored_suffixes() {
        assert!(is_vendored("/app/bundle.min.js"));
        assert!(is_vendored("/proto/types.pb.go"));
        assert!(!is_vendored("/src/bundle.rs"));
    }

    #[test]
    fn vendored_detection_handles_windows_paths() {
        assert!(is_vendored(r"C:\repo\node_modules\pkg\index.js"));
        assert!(is_vendored(r"C:\repo\target\debug\thing.rs"));
        assert!(is_vendored(r"C:\repo\.git\hooks\pre-commit"));
        assert!(is_vendored(r"C:\repo\src\bundle.min.js"));
        assert!(is_vendored(r"C:\repo\src\types.generated.rs"));
        assert!(!is_vendored(r"C:\repo\src\main.rs"));
    }

    #[test]
    fn generated_detection() {
        let dir = tempfile::tempdir().unwrap();
        let gen = dir.path().join("gen.rs");
        std::fs::write(
            &gen,
            "// Code generated by protoc. DO NOT EDIT.\nfn foo() {}",
        )
        .unwrap();
        assert!(is_generated(&gen));

        let normal = dir.path().join("normal.rs");
        std::fs::write(&normal, "fn main() {}\n").unwrap();
        assert!(!is_generated(&normal));
    }

    #[test]
    fn generated_content_detection() {
        let gen = b"// @generated by sqlc\nfn foo() {}";
        assert!(is_generated_content(gen));

        let normal = b"fn main() { println!(\"hello\"); }";
        assert!(!is_generated_content(normal));
    }

    #[test]
    fn walk_finds_source_files() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();
        std::fs::write(dir.path().join("readme.md"), "# hi").unwrap();
        std::fs::write(dir.path().join("lib.py"), "def foo(): pass").unwrap();

        let paths = walk_repo(dir.path());
        let names: Vec<&str> = paths
            .iter()
            .filter_map(|p| p.file_name()?.to_str())
            .collect();
        assert!(names.contains(&"main.rs"), "missing main.rs: {names:?}");
        assert!(names.contains(&"lib.py"), "missing lib.py: {names:?}");
        assert!(!names.contains(&"readme.md"), "should skip .md: {names:?}");
    }

    #[test]
    fn walk_applies_ignore_patterns() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();
        std::fs::create_dir_all(dir.path().join("ignored_src/pkg")).unwrap();
        std::fs::write(
            dir.path().join("ignored_src/pkg/index.js"),
            "export const x = 1;",
        )
        .unwrap();
        std::fs::write(
            dir.path().join("ignored_src/pkg/lib.rs"),
            "pub fn ignored() {}",
        )
        .unwrap();

        let paths = walk_repo_with_ignores(dir.path(), 2_097_152, &["ignored_src".to_string()]);
        let names: Vec<&str> = paths
            .iter()
            .filter_map(|p| p.file_name()?.to_str())
            .collect();
        assert!(names.contains(&"main.rs"));
        assert!(!paths
            .iter()
            .any(|p| p.to_string_lossy().contains("ignored_src")));
    }

    #[test]
    fn walk_applies_glob_ignore_patterns() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();
        std::fs::write(
            dir.path().join("schema.generated.rs"),
            "pub fn generated() {}",
        )
        .unwrap();

        let paths = walk_repo_with_ignores(dir.path(), 2_097_152, &["*.generated.rs".to_string()]);
        let names: Vec<&str> = paths
            .iter()
            .filter_map(|p| p.file_name()?.to_str())
            .collect();
        assert!(names.contains(&"main.rs"));
        assert!(!names.contains(&"schema.generated.rs"));
    }
}
