//! File walker with gitignore and generated-file filtering.

use ignore::WalkBuilder;
use recon_core::lang::Language;
use std::path::{Path, PathBuf};

/// Default ignore patterns for generated/vendored code.
const GENERATED_MARKERS: &[&str] = &[
    "DO NOT EDIT",
    "@generated",
    "Code generated by",
    "AUTO-GENERATED",
    "automatically generated",
];

/// Walk a directory, yielding paths that should be indexed.
pub fn walk_repo(root: &Path) -> Vec<PathBuf> {
    let mut paths = Vec::new();
    let walker = WalkBuilder::new(root)
        .hidden(true)
        .git_ignore(true)
        .git_global(true)
        .git_exclude(true)
        .build();

    for entry in walker {
        let entry = match entry {
            Ok(e) => e,
            Err(_) => continue,
        };
        if !entry.file_type().is_some_and(|ft| ft.is_file()) {
            continue;
        }
        let path = entry.path();
        let lang = Language::from_path(path);
        if lang == Language::Unknown {
            continue;
        }
        // Skip large files (>1 MB)
        if let Ok(meta) = std::fs::metadata(path) {
            if meta.len() > 1_048_576 {
                continue;
            }
        }
        // Skip known vendored/build directories
        let path_str = path.to_string_lossy();
        if is_vendored(&path_str) {
            continue;
        }
        paths.push(path.to_path_buf());
    }
    paths
}

/// Check if a path looks like a generated file by scanning first 8 lines.
pub fn is_generated(path: &Path) -> bool {
    use std::io::{BufRead, BufReader};

    let file = match std::fs::File::open(path) {
        Ok(f) => f,
        Err(_) => return false,
    };
    let reader = BufReader::with_capacity(4096, file);
    for line in reader.lines().take(8) {
        let line = match line {
            Ok(l) => l,
            Err(_) => return false,
        };
        for marker in GENERATED_MARKERS {
            if line.contains(marker) {
                return true;
            }
        }
    }
    false
}

fn is_vendored(path: &str) -> bool {
    let segments = [
        "/node_modules/", "/target/", "/dist/", "/build/", "/.next/",
        "/.venv/", "/__pycache__/", "/vendor/", "/third_party/",
        "/generated/", "/.git/",
    ];
    for seg in &segments {
        if path.contains(seg) {
            return true;
        }
    }
    let suffixes = [".min.js", ".bundle.js", ".pb.go", ".generated."];
    for suf in &suffixes {
        if path.contains(suf) {
            return true;
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vendored_detection() {
        assert!(is_vendored("/foo/node_modules/bar.js"));
        assert!(is_vendored("/foo/target/debug/thing.rs"));
        assert!(!is_vendored("/src/main.rs"));
    }

    #[test]
    fn generated_detection() {
        let dir = tempfile::tempdir().unwrap();
        let gen = dir.path().join("gen.rs");
        std::fs::write(&gen, "// Code generated by protoc. DO NOT EDIT.\nfn foo() {}").unwrap();
        assert!(is_generated(&gen));

        let normal = dir.path().join("normal.rs");
        std::fs::write(&normal, "fn main() {}\n").unwrap();
        assert!(!is_generated(&normal));
    }

    #[test]
    fn walk_finds_source_files() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("main.rs"), "fn main() {}").unwrap();
        std::fs::write(dir.path().join("readme.md"), "# hi").unwrap();
        std::fs::write(dir.path().join("lib.py"), "def foo(): pass").unwrap();

        let paths = walk_repo(dir.path());
        let names: Vec<&str> = paths.iter().filter_map(|p| p.file_name()?.to_str()).collect();
        assert!(names.contains(&"main.rs"), "missing main.rs: {names:?}");
        assert!(names.contains(&"lib.py"), "missing lib.py: {names:?}");
        assert!(!names.contains(&"readme.md"), "should skip .md: {names:?}");
    }
}
